# Generated by Django 4.2.1 on 2023-05-18 16:36

from django.db import migrations, models
import django.db.models.deletion
import manage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to=manage_app.models.upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DicomImage',
        ),
        migrations.AddField(
            model_name='imagep',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.patient'),
        ),
    ]
