# Generated by Django 4.2.1 on 2023-05-19 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_imagep_alter_patient_id_alter_useraccount_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('study_description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.patient')),
            ],
        ),
    ]
