# Generated by Django 4.2.1 on 2023-05-19 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.study')),
            ],
        ),
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.FileField(upload_to=manage_app.models.upload_to_dicom)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.serie')),
            ],
        ),
    ]
