# Generated by Django 4.2.1 on 2023-05-19 10:08

from django.db import migrations, models
import django.db.models.deletion
import manage_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_serie_dicomfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to=manage_app.models.upload_to)),
                ('dicom_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.dicomfile')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCaptioningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model_description', models.TextField()),
                ('model_file', models.FileField(upload_to=manage_app.models.upload_to_caption_model)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model_description', models.TextField()),
                ('model_file', models.FileField(upload_to=manage_app.models.upload_to_segmentation_model)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to=manage_app.models.upload_to_segmentations)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.image')),
                ('segmentation_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.segmentationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.image')),
                ('image_captioning_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.imagecaptioningmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('region_count', models.IntegerField()),
                ('region_id', models.CharField(max_length=255)),
                ('region_shape_attributes_tool_name', models.CharField(max_length=255)),
                ('region_shape_attributes_value', models.TextField()),
                ('region_attributes_purpose', models.CharField(max_length=255)),
                ('region_attributes_value', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_app.image')),
            ],
        ),
    ]
