# Generated by Django 4.2.1 on 2023-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0005_image_imagecaptioningmodel_segmentationmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=31),
        ),
    ]
