# Generated by Django 4.2.1 on 2023-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0006_alter_patient_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='region_attributes_purpose',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='region_attributes_value',
        ),
        migrations.AddField(
            model_name='annotation',
            name='region_attributes_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annotation',
            name='region_attributes_comment_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annotation',
            name='region_attributes_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annotation',
            name='region_attributes_tag_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
