# Generated by Django 4.2.1 on 2023-06-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0007_remove_annotation_region_attributes_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url_name',
            field=models.CharField(null=True),
        ),
    ]
